
/* =============================================================================
SECTION 3: CUSTOMER ANALYSIS

Purpose:
Understand customer behavior by measuring customer value,
purchase frequency, recency, lifespan, and purchasing journeys.

Skills Demonstrated:
- Customer-level analytics
- Customer Lifetime Value (CLV)
- Behavioral analysis
- Date calculations
- Window functions

Business Value:
Identifies valuable customers, purchasing patterns,
and opportunities to improve customer engagement and retention.
============================================================================= */



/* =============================================================================
Q1. TOP 10 CUSTOMERS BY REVENUE

Business Question:
Who are the highest spending customers?

Description:
Calculates total revenue generated by each customer and ranks them to
identify the top 10 highest-value customers based on total spending.
============================================================================= */
select 
c.customer_id,
concat(c.customer_name," ", c.customer_last_name) as customer_full_name,
sum(s.sales_amount) as total_spend
from gold.customers_dim as c
left join gold.sales_fact as s
on c.customer_key = s.customer_key
group by 
c.customer_id,
concat(c.customer_name, " ", c.customer_last_name)
order by total_spend desc
limit 10;




/* =============================================================================
Q2. MONTHLY ACTIVE CUSTOMERS

Business Question:
How many unique customers purchase each month?

Description:
Measures monthly customer activity by counting distinct customers,
orders, and total revenue per month to track engagement trends over time.
============================================================================= */
SELECT
    DATE_FORMAT(order_date, '%Y-%b') AS sales_month,
    COUNT(DISTINCT customer_key) AS unique_customers,
    COUNT(DISTINCT order_number) AS total_orders,
    SUM(sales_amount) AS total_sales
FROM gold.sales_fact
WHERE order_date IS NOT NULL
GROUP BY DATE_FORMAT(order_date, '%Y-%b')
ORDER BY
    MIN(order_date);



/* =============================================================================
Q3. INACTIVE CUSTOMERS (6+ MONTHS)

Business Question:
Which customers have not purchased recently?

Description:
Identifies customers who have not made a purchase in the last 6 months
based on their most recent order date compared to the dataset’s latest
transaction period.
============================================================================= */
    SELECT
    c.customer_key,
    c.customer_number,
    CONCAT(c.customer_name, ' ', c.customer_last_name) AS customer_full_name,
    MAX(s.order_date) AS last_order_date,
    TIMESTAMPDIFF(
        MONTH,
        MAX(s.order_date),
        (SELECT MAX(order_date) FROM gold.sales_fact)
    ) AS months_inactive
FROM gold.sales_fact s
JOIN gold.customers_dim c
    ON s.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.customer_number,
    customer_full_name
HAVING TIMESTAMPDIFF(
           MONTH,
           MAX(s.order_date),
           (SELECT MAX(order_date) FROM gold.sales_fact)
       ) >= 6
ORDER BY months_inactive DESC;



/* =============================================================================
Q4. TOP CUSTOMER REVENUE CONTRIBUTION

Business Question:
Which customers contribute the most to total revenue?

Description:
Calculates each customer's total revenue contribution and percentage share
of overall sales to identify top revenue-driving customers.
============================================================================= */
SELECT
    c.customer_id,
    concat(c.customer_name, " ", c.customer_last_name) as customer_full_name,
    SUM(s.sales_amount) AS total_sales,
    concat(ROUND(SUM(s.sales_amount) * 100 /(SELECT SUM(sales_amount) FROM gold.sales_fact), 2), "%") AS sales_percentage
FROM gold.sales_fact AS s
LEFT JOIN gold.customers_dim AS c
    ON s.customer_key = c.customer_key
GROUP BY 
c.customer_id,
concat(c.customer_name, " ", c.customer_last_name)
ORDER BY total_sales DESC
LIMIT 20;




/* =============================================================================
Q5. AVERAGE CUSTOMER AGE

Business Question:
What is the average age of customers?

Description:
Calculates the average customer age using birthdate and latest transaction
date to understand overall customer demographics.
============================================================================= */
SELECT
    ROUND(AVG(TIMESTAMPDIFF(YEAR, birthdate, max_date)), 2) AS avg_customer_age
FROM gold.customers_dim
CROSS JOIN (
    SELECT MAX(order_date) AS max_date
    FROM gold.sales_fact
) t;



/* =============================================================================
Q6. ABOVE-AVERAGE SPENDING CUSTOMERS

Business Question:
Which customers spend more than the average customer?

Description:
Identifies customers whose total spending exceeds the average customer
spending level using a subquery comparison.
============================================================================= */
SELECT 
    CONCAT(c.customer_name, ' ', c.customer_last_name) AS customer_full_name,
    ROUND(SUM(s.sales_amount), 2) AS total_spent,
    ROUND(AVG(s.sales_amount), 2) AS avg_spent
FROM customers_dim AS c
LEFT JOIN sales_fact AS s ON c.customer_key = s.customer_key
GROUP BY c.customer_key, c.customer_name, c.customer_last_name
HAVING SUM(s.sales_amount) > (
    SELECT AVG(total_spending)
    FROM (
        SELECT SUM(sales_amount) AS total_spending
        FROM sales_fact
        GROUP BY customer_key
    ) AS customer_totals
);




/* =============================================================================
Q7. CONSISTENT YEARLY BUYERS

Business Question:
Which customers purchase every year?

Description:
Finds customers who have made purchases in all available years in the
dataset, indicating strong long-term engagement.
============================================================================= */
SELECT 
    CONCAT(c.customer_name, ' ', c.customer_last_name) AS customer_full_name,
    COUNT(DISTINCT YEAR(s.order_date)) AS years_purchased
FROM customers_dim AS c
INNER JOIN sales_fact AS s ON c.customer_key = s.customer_key
GROUP BY c.customer_key, c.customer_name, c.customer_last_name
HAVING COUNT(DISTINCT YEAR(s.order_date)) = (
    SELECT COUNT(DISTINCT YEAR(order_date))
    FROM sales_fact
);



/* =============================================================================
Q8. CUSTOMER LIFETIME VALUE (CLV)

Business Question:
How valuable is each customer?

Description:
Calculates customer value using total orders, total revenue, average order
value, first purchase date, and last purchase date to evaluate long-term
customer contribution.
============================================================================= */
select 
concat(c.customer_name, " ", c.customer_last_name) as customer_full_name,
count(distinct s.order_number) as total_order,
sum(s.sales_amount) as total_sales,
round(avg(s.sales_amount), 2) as Average_sales,
MIN(DATE_FORMAT(s.order_date, '%Y-%m-%d')) AS first_order_date,
MAX(DATE_FORMAT(s.order_date, '%Y-%m-%d')) AS last_order_date
from customers_dim as c
left join sales_fact as s
on c.customer_key = s.customer_key
group by
c.customer_key, 
c.customer_name,
c.customer_last_name
order by total_sales desc;



/* =============================================================================
Q9. CUSTOMER LIFESPAN ANALYSIS

Business Question:
How long does a customer remain active?

Description:
Measures the time difference between first and last purchase to calculate
customer lifespan in days, months, and years, and segments customers based
on activity duration.
============================================================================= */

with customer_lifespan as (
select 
concat(c.customer_name, " ", c.customer_last_name) as customer_full_name,
MIN(DATE_FORMAT(s.order_date, '%Y-%m-%d')) AS first_purchase_date,
MAX(DATE_FORMAT(s.order_date, '%Y-%m-%d')) AS last_purchase_date,
datediff(MAX(DATE_FORMAT(s.order_date, '%Y-%m-%d')), MIN(DATE_FORMAT(s.order_date, '%Y-%m-%d'))) as lifespan_days,
ROUND(DATEDIFF(MAX(s.order_date), MIN(s.order_date)) / 30, 1)  AS lifespan_months,
ROUND(DATEDIFF(MAX(s.order_date), MIN(s.order_date)) / 365, 1) AS lifespan_years
from sales_fact as s
join customers_dim as c
on s.customer_key = c.customer_key
group by c.customer_key,
c. customer_name,
c.customer_last_name)

select 
customer_full_name,
first_purchase_date,
last_purchase_date,
lifespan_days,
lifespan_months,
lifespan_years,
case 
when lifespan_days is null then "Not available"
when lifespan_days = 0 then "One time buyer"
when lifespan_days <= 180 then "short term buyer"
when  lifespan_days <= 365 then "Mid term buyer"
else "long term buyer"
end as customer_segment
from customer_lifespan
order by lifespan_days desc;



/* =============================================================================
Q10. CUSTOMER RECENCY ANALYSIS

Business Question:
How long has it been since a customer's last purchase?

Description:
Calculates the number of days since the most recent purchase and segments
customers into Active, At Risk, Slipping Away, or Churned categories based
on recency.
============================================================================= */

select 
concat(c.customer_name, " ", c.customer_last_name) as customer_full_name,
MAX(DATE_FORMAT(s.order_date, '%Y-%m-%d')) AS last_purchase_date,
datediff((select max(order_date) from gold.sales_fact),  MAX(DATE_FORMAT(s.order_date, '%Y-%m-%d'))) as recency_days,
case
when datediff((select max(order_date) from gold.sales_fact),  MAX(DATE_FORMAT(s.order_date, '%Y-%m-%d'))) is null then "Date is not available"
 when datediff((select max(order_date) from gold.sales_fact),  MAX(DATE_FORMAT(s.order_date, '%Y-%m-%d'))) <= 30 then "Active"
 when datediff((select max(order_date) from gold.sales_fact),  MAX(DATE_FORMAT(s.order_date, '%Y-%m-%d'))) <= 90 then "At risk"
 when datediff((select max(order_date) from gold.sales_fact),  MAX(DATE_FORMAT(s.order_date, '%Y-%m-%d'))) <= 180 then "Slipping away"
 else "churned" 
 end as recency_segment
 from sales_fact as s
 inner join customers_dim as c
 on s.customer_key = c.customer_key
 group by 
 c.customer_key,
 c.customer_name,
 c.customer_last_name
 order by recency_days;



/* =============================================================================
Q11. CUSTOMER PURCHASE FREQUENCY

Business Question:
How often do customers make purchases?

Description:
Calculates purchase frequency by measuring orders per month based on
customer lifespan and total orders, then segments customers into behavior
groups such as Frequent, Regular, or Occasional buyers.
============================================================================= */

WITH purchase_frequency AS (
    SELECT 
        CONCAT(c.customer_name, ' ', c.customer_last_name) AS customer_full_name,
        COUNT(DISTINCT s.order_number) AS total_order,
        MIN(s.order_date) AS first_purchase_date,
        MAX(s.order_date) AS last_purchase_date,
        DATEDIFF(MAX(s.order_date), MIN(s.order_date)) AS lifespan_days,
        ROUND(DATEDIFF(MAX(s.order_date), MIN(s.order_date)) / 30, 1)  AS lifespan_months,
        ROUND(COUNT(DISTINCT s.order_number) / NULLIF(ROUND(DATEDIFF(MAX(s.order_date), MIN(s.order_date)) / 30, 1), 0), 2)  AS orders_per_month
    FROM sales_fact AS s
    INNER JOIN customers_dim AS c ON s.customer_key = c.customer_key
    GROUP BY c.customer_key, c.customer_name, c.customer_last_name
)
SELECT 
    customer_full_name,
    total_order,
    first_purchase_date,
    last_purchase_date,
    lifespan_months,
    orders_per_month,
    CASE 
        WHEN total_order = 1 THEN 'One time buyer'
        WHEN orders_per_month >= 2 THEN 'Frequent buyer'
        WHEN orders_per_month >= 1 THEN 'Regular buyer'
        ELSE 'Occasional buyer'
    END AS frequency_segment
FROM purchase_frequency
ORDER BY orders_per_month DESC;

